### ISSUE TITLE
Skipping Channels During Scan

### ISSUE THREAD

**Issue by 1jnewcs** [armel/uv-k5-chirp-driver#49]
In chirp; the option to 'skip', gives no options. Normally there is an option 'S' to skip said channel during scanning. 

Also, setting some channels to: 'tx lockout': on, Doesn't lock them (doesn't show lock icon)

3.8.0

![chirpwx_MCZQl9cGxE](https://github.com/user-attachments/assets/4c147d64-f2dd-4dda-9ce5-f341cd447bad)

thx!!

**Comment by armel** [comment]
First of all, good morning—it's free to say it.

Secondly, the Skip column **is not added by the driver** specific to my firmware, but by [Chirp itself](https://chirpmyradio.com/projects/chirp/wiki/MemoryEditorColumns#Understanding-CHIRPs-columns). This is a **standard column**. And I don't think it's possible to remove it. 

Thirdly, I believe you're referring to the TXLock column (and not TXLockout). I suggest you read the [documentation](https://github.com/armel/uv-k5-firmware-custom/wiki/Radio-operation#about-the-flock-and-txlock-menus) if needed to understand how it works. Otherwise, please provide a concrete example of the issue.

Armel F4HWN.

**Comment by armel** [comment]
Sounds good to me. You understand perfectly. 
Thank you.

**Comment by 1jnewcs** [comment]
Thank you and thanks so much for your work
